services:
  - type: web
    name: my-line-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
      - key: CHANNEL_SECRET
        sync: false
